### /crawl

### GET test
get http://localhost:9000/crawl/test

### GET specified user crawled data
get http://localhost:9000/crawl/sharifi

### GET all subscribed users crawled data
get http://localhost:9000/crawl/everyone




### /user

### GET all saved data from the db
get http://localhost:9000/user/subscriptions

### GET specified user data from the db
get http://localhost:9000/user/username@gmail.com

### GET verify specified user
get http://localhost:9000/user/verify/5df0205777c2212470e76111

### GET unsubscribe specified user
get http://localhost:9000/user/unsubscribe/5df54c02013b55168cbd2f5d

### PUT subscribe user
put http://localhost:9000/user/subscribe
Content-Type: application/json

{
  "username": "escyth",
  "email": "username@gmail.com"
}




### /mail

### GET mass mailing
get http://localhost:9000/mail/mass

### GET single user mailing
get http://localhost:9000/mail/username@gmail.com

### testing emails
### no data: escyth
### has data: sharifi