### /crawl

### GET test
GET http://localhost:9000/crawl/test

### GET user crawled data
GET http://localhost:9000/crawl/sharifi

### GET all subscribed users crawled data
GET http://localhost:9000/crawl/everyone




### /user

### GET all saved data from the db
GET http://localhost:9000/user/subscriptions

### GET user data from the db
GET http://localhost:9000/user/username@gmail.com

### GET verify user
GET http://localhost:9000/user/verify/5df0205777c2212470e76111

### GET unsubscribe user
GET http://localhost:9000/user/unsubscribe/5df54c02013b55168cbd2f5d

### GET update user
GET http://localhost:9000/user/update/5df0205777c2212470e76111/diobrando

### PUT subscribe user
PUT http://localhost:9000/user/subscribe
Content-Type: application/json

{
  "username": "escyth",
  "email": "username@gmail.com"
}




### /mail

### GET mass mailing
GET http://localhost:9000/mail/mass

### GET single user mailing
GET http://localhost:9000/mail/username@gmail.com

### testing emails
### no data: escyth
### has data: sharifi