### /crawl

### get mock crawled data
GET http://localhost:9000/crawl/test

### get user crawled data
GET http://localhost:9000/crawl/sharifi

### get all subscribed users crawled data
GET http://localhost:9000/crawl/everyone

### /users

### get all saved data from the db
GET http://localhost:9000/users/everyone

### get user data from the db
GET http://localhost:9000/users/username@gmail.com

### verify user
GET http://localhost:9000/users/verify/5df58a4563bf5c223c07a1fd

### unsubscribe user
GET http://localhost:9000/users/unsubscribe/5df54c02013b55168cbd2f5d

### update user
GET http://localhost:9000/users/update/5df0205777c2212470e76111/diobrando

### subscribe user
PUT http://localhost:9000/users/subscribe
Content-Type: application/json

{
  "username": "escyth",
  "email": "username@gmail.com"
}

### /mail

### mail everyone
GET http://localhost:9000/mail/everyone

### single user mailing
GET http://localhost:9000/mail/username@gmail.com

### testing emails
### no data: escyth
### has data: sharifi