### /crawl

### crawlController.everyone
### save all users crawled data to the db
### /crawl/
### API_KEY_PRIVATE
GET http://localhost:9000/crawl/
X-API-Key: xDzpq8mI5PgCcNH4

### crawlController.specified
### get mock crawled data
### /crawl/tt
### API_KEY_PUBLIC
GET http://localhost:9000/crawl/tt
X-API-Key: o6EWhXFY15ODhD2Q

### crawlController.specified
### get user crawled data
### /crawl/{username}
### API_KEY_PUBLIC
GET http://localhost:9000/crawl/sharifi
X-API-Key: o6EWhXFY15ODhD2Q

###
###
###

### /users

### usersController.everyone
### get all users
### /users/
### API_KEY_PRIVATE
GET http://localhost:9000/users/
X-API-Key: xDzpq8mI5PgCcNH4

### usersController.subscribe
### subscribe user
### /users/subscribe
### API_KEY_PUBLIC
PUT http://localhost:9000/users/subscribe
X-API-Key: o6EWhXFY15ODhD2Q
Content-Type: application/json

{
  "username": "escyth",
  "email": "username@gmail.com"
}

### usersController.verification
### verify user
### /users/verification?id={id}&email={email}
### API_KEY_PUBLIC
PATCH http://localhost:9000/users/verification?id=5df0205777c2212470e76111&email=aturaden@gmail.com
X-API-Key: o6EWhXFY15ODhD2Q

### usersController.update
### update user
### /users/update?id={id}&email={email}&username={username}
### API_KEY_PUBLIC
PATCH http://localhost:9000/users/update?id=5df0205777c2212470e76111&email=username@gmail.com&username=diobrando
X-API-Key: o6EWhXFY15ODhD2Q


### usersController.unsubscribe
### unsubscribe user
### /users/unsubscribe?id={id}&email={email}
### API_KEY_PUBLIC
DELETE http://localhost:9000/users/unsubscribe?id=5e2fc57be502051bccbd23f5&email=username@gma123asdasdil.com
X-API-Key: o6EWhXFY15ODhD2Q

### usersController.specified
### get specified user
### /users/{email}
### API_KEY_PRIVATE
GET http://localhost:9000/users/username@gmail.com
X-API-Key: xDzpq8mI5PgCcNH4

###
###
###

### /mail

### mailController.specified
### mail everyone
### /mail/
### API_KEY_PRIVATE
GET http://localhost:9000/mail/
X-API-Key: xDzpq8mI5PgCcNH4

### mailController.specified
### single user mailing
### /mail/{email}
### API_KEY_PRIVATE
GET http://localhost:9000/mail/username@gmail.com
X-API-Key: xDzpq8mI5PgCcNH4

### testing emails
### no data: escyth
### has data: sharifi